version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: test-jaview-mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: jaview_test
    volumes:
      - ./data/db:/data/db
    networks:
      - JaViewNET
    restart: always

  mongo-express:
    image: mongo-express
    container_name: test_jaview_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: "mongodb://root:password@mongodb:27017/?authSource=admin"
      ME_CONFIG_BASICAUTH_USERNAME: express
      ME_CONFIG_BASICAUTH_PASSWORD: express
    depends_on:
      - "mongodb"
    restart: always
    networks:
    - JaViewNET

networks:
  JaViewNET:
    driver: bridge